### ISSUE TITLE
Have npm build

### ISSUE THREAD

**Issue by pjpsoares** [mobxjs/mobx-react-typescript-boilerplate#12]
My idea would be to have npm build generating a bundle folder with all the required files to be able to easily deploy somewhere that wouldn't actually require a node server.
I'm going to do this for my project, if you'd like I'm more than happy to make a PR for this.

**Comment by mweststrate** [comment]
This boilerplate serves more like a minimal configuration setup example,
then as real project to start with, as it has no other interesting features
(like css compilation, linting etc).

Op za 4 nov. 2017 om 16:50 schreef Paulo Soares <notifications@github.com>:
