### ISSUE TITLE
Webpack compile error

### ISSUE THREAD

**Issue by FDN73** [mobxjs/mobx-react-typescript-boilerplate#16]
Hello,
running npm install followed by npm start:

ERROR in [at-loader] ./node_modules/mobx/lib/utils/utils.d.ts:1:23 
    TS2688: Cannot find type definition file for 'node'.

ERROR in [at-loader] ./node_modules/mobx/lib/utils/utils.d.ts:39:48 
    TS2304: Cannot find name 'Iterator'.
webpack: Failed to compile.

**Comment by mweststrate** [comment]
Duplicate of: https://github.com/mobxjs/mobx/issues/1387
