### ISSUE TITLE
Live reloading doesn't work?

### ISSUE THREAD

**Issue by jussiarpalahti** [mobxjs/mobx-react-typescript-boilerplate#2]
I tested with this boilerplate and the regular React based. It seems that even with most trivial changes the live reload complains that live reload can't be done and requires full browser reload. I don't mind losing the app state, but full reload does take a couple seconds while regular reloading usually does in 1-2.

Steps to reproduce:

 * clone the repository
 * npm install
 * npm start
 * open in browser
 * edit src/index.tsx and add one tag (for instance ```<h1>test</h1>```) after first div [here](https://github.com/mobxjs/mobx-react-typescript-boilerplate/blob/master/src/index.tsx#L25)
 * console should now display a message about modules can't be hot updated and full reload required, while the page stays the same

I tested with Node versions 4.x and 5.x, both OS X and Ubuntu 14.04. I have got hot reload to work before with other projects, and am a bit baffled at why this one doesn't work for me. I also tested updating and downgrading reload components to other versions, but this didn't affect the outcome.

I managed to get a React transform based boilerplate with Webpack HMR API to work, but that was somewhat unstable. This version is [here](https://github.com/jussiarpalahti/gatherer), but I wouldn't recommend using that. I just gobbled it together from other examples...

**Comment by mweststrate** [comment]
Yes that is actually correct, probably I should remove hot reloading form the boilerplate. Live reloading will only properly for files that just contains React components (or are further stateless). Normally you put these components in separate files in which case it will work (usually). But to enable people to grasp boilerplate quickly I've put everything in a single file. 

What would you like better? A simpler boiler plate with HMR or one with multiple files?

**Comment by jussiarpalahti** [comment]
Well, I prefer to have some form of live reloading. I haven't realized it can be so fiddly to get it working. HMR is plastered with "unstable" and "WIP" notices, so I'm not keen to trust that yet. I decided to use that when other ways didn't work.

I think I'd prefer multiple files that "just" work with reloading, since it's especially useful at learning stage where you try things out. When app state gets bigger and you're developing some feature that requires specific app state the usefulness of reloading lessens.

If reloading could be configured to only replace code and start the app from scratch (like happens with initial load and full reload), I think the user experience would be good enough. I tried to look for ways to do this, but webpack's implementation seems to be a black box you can't control. JSPM does everything on the client side dynamically and Amok is very low level.
