### ISSUE TITLE
console error "cannot find module 'react'"

### ISSUE THREAD

**Issue by DerekLiang** [mobxjs/mobx-react-typescript-boilerplate#8]
Here is the console log after following the instructions in the readme.
....
  [245] ./~/react/lib/ReactDOMNullInputValuePropHook.js 1.41 kB {0} [built]
  [246] ./~/mobx/lib/mobx.js 104 kB {0} [built]
  [247] ./~/mobx-react/index.js 34.1 kB {0} [built]
  [248] ./~/mobx-react-devtools/index.js 41.3 kB {0} [built]

ERROR in [default] xxxx\mobx-react-typescript-boilerplate\node_modules\@types\react-dom\react-dom.server.d.ts:2:30
Cannot find module 'react'.

**Comment by Rurik19** [comment]
That is awesome-typescript-loader bug.  Use ts-loader or just neglect it.

**Comment by mweststrate** [comment]
I just did a fresh install, but didn't get the same error. Which node and npm version do you have installed?

**Comment by DerekLiang** [comment]
node v6.1.0
npm v3.8.6

**Comment by benjamingr** [comment]
@DerekLiang can you please check again now?

**Comment by munkeyxis** [comment]
I get this error too. node v6.10.3 npm v3.10.10. windows.

**Comment by benjamingr** [comment]
You forgot to `not install` probably
